// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyMkIYlG0TBJ9OOyoLG3H6F4G7gkR5gSc',
    appId: '1:690351337410:web:4dbab9fb12405ca735b05b',
    messagingSenderId: '690351337410',
    projectId: 'spotify-clone-0102020',
    authDomain: 'spotify-clone-0102020.firebaseapp.com',
    storageBucket: 'spotify-clone-0102020.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPHdfBgPJzFVaCs_QL4mV8RJVP1pOqeBk',
    appId: '1:690351337410:android:d4541881e97b81c835b05b',
    messagingSenderId: '690351337410',
    projectId: 'spotify-clone-0102020',
    storageBucket: 'spotify-clone-0102020.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAspGSKr1CPNOcP3QmmZK34DQ8RqmixU1k',
    appId: '1:690351337410:ios:cb419608ba91d0de35b05b',
    messagingSenderId: '690351337410',
    projectId: 'spotify-clone-0102020',
    storageBucket: 'spotify-clone-0102020.appspot.com',
    iosBundleId: 'com.example.quesso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAspGSKr1CPNOcP3QmmZK34DQ8RqmixU1k',
    appId: '1:690351337410:ios:cb419608ba91d0de35b05b',
    messagingSenderId: '690351337410',
    projectId: 'spotify-clone-0102020',
    storageBucket: 'spotify-clone-0102020.appspot.com',
    iosBundleId: 'com.example.quesso',
  );
}
